<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CTU-PSU" ignored="0" name="testName" tests="6" failures="1" timestamp="10 Oct 2019 08:15:15 GMT" time="0.025" errors="0">
  <testcase name="test1" time="0.0" classname="casest.BasicCase"/>
  <testcase name="test2" time="0.001" classname="casest.BasicCase">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at casest.BasicCase.test2(casest.BasicCase.java:33)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="casest.BasicCase"/>
  <testcase name="test1" time="0.0" classname="BasicCase2"/>
  <testcase name="test2" time="0.0" classname="BasicCase2"/>
  <testcase name="test3" time="0.001" classname="BasicCase2"/>
</testsuite> <!-- testName -->
